--B501 - DATABASE SYSTEMS

CREATE DATABASE ENTV
GO
USE ENTV
GO

CREATE TABLE [Staff] (
	StaffID CHAR(5) PRIMARY KEY CHECK (StaffID LIKE 'ST[0-9][0-9][0-9]'),
	StaffName VARCHAR(50) NOT NULL,
	StaffEmail VARCHAR(50) NOT NULL,
	StaffGender VARCHAR(10) NOT NULL,
	StaffPhone VARCHAR(15) NOT NULL,
	StaffAddress VARCHAR(50) NOT NULL,
	StaffSalary INT NOT NULL,
	StaffDOB DATE NOT NULL
);

CREATE TABLE [Customer] (
	CustomerID CHAR(5) PRIMARY KEY CHECK (CustomerID LIKE 'CU[0-9][0-9][0-9]'),
	CustomerName VARCHAR(50) NOT NULL,
	CustomerEmail VARCHAR(50) NOT NULL,
	CustomerGender VARCHAR(10) NOT NULL,
	CustomerPhone VARCHAR(15) NOT NULL,
	CustomerAddress VARCHAR(50) NOT NULL,
	CustomerDOB DATE NOT NULL
);

CREATE TABLE [Vendor] (
	VendorID CHAR(5) PRIMARY KEY CHECK (VendorID LIKE 'VE[0-9][0-9][0-9]'),
	VendorName VARCHAR(50) NOT NULL,
	VendorEmail VARCHAR(50) NOT NULL,
	VendorPhone VARCHAR(15) NOT NULL,
	VendorAddress VARCHAR(50) NOT NULL
);

CREATE TABLE [Brand] (
	BrandID CHAR(5) PRIMARY KEY CHECK (BrandID LIKE 'TB[0-9][0-9][0-9]'),
	BrandName VARCHAR(50) NOT NULL
);

CREATE TABLE [Television] (
	TelevisionID CHAR(5) PRIMARY KEY CHECK (TelevisionID LIKE 'TE[0-9][0-9][0-9]'),
	BrandID CHAR(5) FOREIGN KEY REFERENCES Brand(BrandID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	TelevisionName VARCHAR(50) NOT NULL,
	TelevisionPrice INT NOT NULL CHECK(TelevisionPrice BETWEEN 1000000 AND 20000000)
);


CREATE TABLE [PurchaseTransaction] (
	PurchaseTransactionID CHAR(5) PRIMARY KEY CHECK (PurchaseTransactionID LIKE 'PE[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	VendorID CHAR(5) FOREIGN KEY REFERENCES Vendor(VendorID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseTransactionDate DATE NOT NULL
);

CREATE TABLE [PurchaseTransactionDetail] (
	PurchaseTransactionID CHAR(5) FOREIGN KEY REFERENCES PurchaseTransaction(PurchaseTransactionID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	TelevisionID CHAR(5) FOREIGN KEY REFERENCES Television(TelevisionID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	PurchaseQuantity INT NOT NULL,
	PRIMARY KEY(PurchaseTransactionID, TelevisionID)
);

CREATE TABLE [SalesTransaction] (
	SalesTransactionID CHAR(5) PRIMARY KEY CHECK (SalesTransactionID LIKE 'SA[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES Staff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	CustomerID CHAR(5) FOREIGN KEY REFERENCES Customer(CustomerID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SalesTransactionDate DATE NOT NULL
);

CREATE TABLE [SalesTransactionDetail] (
	SalesTransactionID CHAR(5) FOREIGN KEY REFERENCES SalesTransaction(SalesTransactionID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	TelevisionID CHAR(5) FOREIGN KEY REFERENCES Television(TelevisionID) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	SalesQuantity INT NOT NULL,
	PRIMARY KEY(SalesTransactionID, TelevisionID)
);
